### ISSUE TITLE
Pi Sound Support

### ISSUE THREAD

**Issue by sigkill** [dwhinham/mt32-pi#42]
Let me know where to send a PiSound, after reading some of the other things you're working on, I think it would benefit both projects to send you one for development purposes.

**Comment by dwhinham** [comment]
Awesome! Thankyou for this - I've replied to your DM! 🙂

**Comment by dwhinham** [comment]
I received a Pisound from @sigkill last week and I've got it working! 😀
Many thanks for getting one to me!

A test build is available here: https://github.com/dwhinham/mt32-pi/actions/runs/389044086

It should be automatically detected - all you need to do to the config file is ensure that:

- `output_device = i2s`
- `sample_rate` is set to either `48000`, `96000`, or `192000` (the only rates supported by the Pisound

You'll know it's been detected because the MIDI IN/OUT LEDs will flash once on startup.

**Comment by sigkill** [comment]
Thank you! Tested it with the settings and kernel from the https://github.com/dwhinham/mt32-pi/actions/runs/389044086 test build (the one that was included in the build worked.) I tested on a Raspberry Pi 3B+ with a version 1.0 PiSound card, and an Atari 1040 STE. Both were able to send MIDI. Rates 48000, 96000, 192000 all confirmed.

Awesome job! Thank you for getting this working.

**Comment by dwhinham** [comment]
Excellent, thanks for testing!

Meanwhile, the patch to Circle required to get this working has been upstreamed: https://github.com/rsta2/circle/pull/167

I'll include this driver in the next release. 😃
